WebEngine.Web/ViewModels/Product/Filter.cs
// -----------------------------------------------------------------------
// <copyright file="Filter.cs" author="Dzmitry Prakapenka">
//     All rights reserved.
// </copyright>
// -----------------------------------------------------------------------

namespace WebEngine.Web.ViewModels.Product
{
	#region Usings

	using System.Collections.Generic;

	#endregion

	/// <summary>
	/// <see cref="Filter"/> class.
	/// </summary>
	public class Filter
	{
		/// <summary>
		/// Gets or sets filter properties.
		/// </summary>
		public IList<FilterProperty> Properties { get; set; }

		/// <summary>
		/// Gets or sets category.
		/// </summary>
		public int CategoryId { get; set; }

		/// <summary>
		/// Gets or sets current page.
		/// </summary>
		public int CurrentPage { get; set; }
	}
}

WebEngine.Web/ViewModels/Product/FilterItemView.cs
// -----------------------------------------------------------------------
// <copyright file="FilterItemView.cs" author="Dzmitry Prakapenka">
//     All rights reserved.
// </copyright>
// -----------------------------------------------------------------------

namespace WebEngine.Web.ViewModels.Product
{
	#region Usings

	using System.Collections.Generic;

	#endregion

	/// <summary>
	/// <see cref="FilterItemView"/> class.
	/// </summary>
	public class FilterItemView
	{
		public int PropertyId { get; set; }

		public string PropertyName { get; set; }

		public string FilterItemType { get; set; }

		public IEnumerable<string> FilterItemValues { get; set; }
	}
}

WebEngine.Web/ViewModels/Product/FilterProperty.cs
// -----------------------------------------------------------------------
// <copyright file="FilterProperty.cs" author="Dzmitry Prakapenka">
//     All rights reserved.
// </copyright>
// -----------------------------------------------------------------------

namespace WebEngine.Web.ViewModels.Product
{
	#region Usings


	#endregion

	/// <summary>
	/// <see cref="FilterProperty"/> class.
	/// </summary>
	public class FilterProperty
	{
		/// <summary>
		/// Gets or sets id.
		/// </summary>
		public int Id { get; set; }

		/// <summary>
		/// Gets or sets value.
		/// </summary>
		public string Value { get; set; }

		/// <summary>
		/// Gets or sets a value idicating whether property is range.
		/// </summary>
		public bool IsRange { get; set; }

		/// <summary>
		/// Gets or sets operator.
		/// </summary>
		public char Operator { get; set; }
	}
}

WebEngine.Web/ViewModels/Product/FullProductView.cs
// -----------------------------------------------------------------------
// <copyright file="FullProductView.cs" author="Dzmitry Prakapenka">
//     All rights reserved.
// </copyright>
// -----------------------------------------------------------------------

namespace WebEngine.Web.ViewModels.Product
{
	#region Usings

	using System.Collections.Generic;

	#endregion

	/// <summary>
	/// <see cref="FullProductView"/> class.
	/// </summary>
	public class FullProductView
	{
		public int ProductId { get; set; }

		public string ProductName { get; set; }

		public IList<ProductPropertyView> Properties { get; set; }

		public IList<ProductBaseProperty> BaseProperties { get; set; }
	}
}

WebEngine.Web/ViewModels/Product/ProductBaseProperty.cs
// -----------------------------------------------------------------------
// <copyright file="ProductProperty.cs" author="Dzmitry Prakapenka">
//     All rights reserved.
// </copyright>
// -----------------------------------------------------------------------

namespace WebEngine.Web.ViewModels.Product
{
	#region Usings

	#endregion

	/// <summary>
	/// <see cref="ProductProperty"/> class.
	/// </summary>
	public class ProductBaseProperty
	{
		public int Id { get; set; }

		public string Name { get; set; }
	}
}

WebEngine.Web/ViewModels/Product/ProductFilterView.cs
// -----------------------------------------------------------------------
// <copyright file="FilterView.cs" author="Dzmitry Prakapenka">
//     All rights reserved.
// </copyright>
// -----------------------------------------------------------------------

namespace WebEngine.Web.ViewModels.Product
{
	#region Usings

	using System.Collections.Generic;

	using Core.Entities;

	#endregion

	/// <summary>
	/// <see cref="ProductFilterView"/> class.
	/// </summary>
	public class ProductFilterView
	{
		/// <summary>
		/// Gets or sets product filter items.
		/// </summary>
		public IList<ProductFilterItem> Items { get; set; }
	}
}

WebEngine.Web/ViewModels/Product/ProductFullView.cs
// -----------------------------------------------------------------------
// <copyright file="ProductFullView.cs" author="Dzmitry Prakapenka">
//     All rights reserved.
// </copyright>
// -----------------------------------------------------------------------

namespace WebEngine.Web.ViewModels.Product
{
	#region Usings

	using System.Collections.Generic;

	#endregion

	/// <summary>
	/// TODO: Update summary.
	/// </summary>
	public class ProductFullView
	{
		public int ProductId { get; set; }

		public string Name { get; set; }

		public IList<ProductPropertyView> Properties { get; set; }
	}
}

WebEngine.Web/ViewModels/Product/ProductListView.cs
// -----------------------------------------------------------------------
// <copyright file="ProductListView.cs" author="Dzmitry Prakapenka">
//     All rights reserved.
// </copyright>
// -----------------------------------------------------------------------

namespace WebEngine.Web.ViewModels.Product
{
	#region Usings

	using System.Collections.Generic;

	#endregion

	/// <summary>
	/// <see cref="ProductListView"/> class.
	/// </summary>
	public class ProductListView
	{
		/// <summary>
		/// Gets or sets category name.
		/// </summary>
		public string CategoryName { get; set; }

		/// <summary>
		/// Gets or sets category view name.
		/// </summary>
		public string CategoryViewName { get; set; }

		/// <summary>
		/// Gets or sets products.
		/// </summary>
		public IEnumerable<ProductView> Products { get; set; }

		/// <summary>
		/// Gets or sets current page.
		/// </summary>
		public int CurrentPage { get; set; }

		/// <summary>
		/// Gets or sets total pages.
		/// </summary>
		public int TotalPages { get; set; }
	}
}

WebEngine.Web/ViewModels/Product/ProductPageView.cs
// -----------------------------------------------------------------------
// <copyright file="ProductsPageView.cs" author="Dzmitry Prakapenka">
//     All rights reserved.
// </copyright>
// -----------------------------------------------------------------------

namespace WebEngine.Web.ViewModels.Product
{
	#region Usings

	using System.Collections.Generic;

	#endregion

	/// <summary>
	/// <see cref="ProductPageView"/> class.
	/// </summary>
	public class ProductPageView
	{
		/// <summary>
		/// Gets or sets products.
		/// </summary>
		public IEnumerable<ProductView> Products { get; set; }

		/// <summary>
		/// Gets or sets filter items.
		/// </summary>
		public IEnumerable<FilterItemView> FilterItems { get; set; }

		/// <summary>
		/// Gets or sets category name.
		/// </summary>
		public string CategoryName { get; set; }

		/// <summary>
		/// Gets or sets category view name.
		/// </summary>
		public string CategoryViewName { get; set; }

		/// <summary>
		/// Gets or sets category id.
		/// </summary>
		public int CategoryId { get; set; }

		/// <summary>
		/// Gets or sets current page.
		/// </summary>
		public int CurrentPage { get; set; }

		/// <summary>
		/// Gets or sets total pages.
		/// </summary>
		public int TotalPages { get; set; }
	}
}

WebEngine.Web/ViewModels/Product/ProductPropertyView.cs
// -----------------------------------------------------------------------
// <copyright file="ProductPropertyView.cs" author="Dzmitry Prakapenka">
//     All rights reserved.
// </copyright>
// -----------------------------------------------------------------------

namespace WebEngine.Web.ViewModels.Product
{
	#region Usings

	#endregion

	/// <summary>
	/// TODO: Update summary.
	/// </summary>
	public class ProductPropertyView
	{
		public int PropertyId { get; set; }

		public int BasePropertyId { get; set; }

		public string PropertyName { get; set; }

		public string Value { get; set; }

		public string SizeValue { get; set; }
	}
}

WebEngine.Web/Controllers/ProductController.cs
// -----------------------------------------------------------------------
// <copyright file="SmartPhoneController.cs" author="Dzmitry Prakapenka">
//     All rights reserved.
// </copyright>
// -----------------------------------------------------------------------

namespace WebEngine.Web.Controllers
{
	#region Usings

	using System.Collections.Generic;
	using System.Linq;
	using System.Threading.Tasks;

	using Microsoft.AspNetCore.Mvc;

	using WebEngine.Core.Entities;
	using WebEngine.Core.Interfaces;
	using WebEngine.Web.ViewModels.Product;
	using WebEngine.Core.Filters;
	using Core.PageModels;
	#endregion

	/// <summary>
	/// <see cref="ProductController"/> class.
	/// </summary>
	public class ProductController : Controller
	{
		#region Private fields

		private readonly IProductRepository _productRepository;

		private readonly ICategotyRepository _categoryRepository;

		private readonly IProductFilterRepository _productFilterRepository;

		private readonly IProductPageRepository _productPageRepository;

		private const int PAGE_SIZE = 30;

		#endregion

		#region Constructors

		public ProductController(
			IProductRepository productRepository,
			ICategotyRepository categoryRepository,
			IProductFilterRepository productFilterRepository,
			IProductPageRepository productPageRepository)
		{
			_productRepository = productRepository;
			_categoryRepository = categoryRepository;
			_productFilterRepository = productFilterRepository;
			_productPageRepository = productPageRepository;
		}

		#endregion

		[HttpPost]
		public async Task<IActionResult> Index([FromBody]Filter filter)
		{
			if (filter != null)
			{
				Category category = await _categoryRepository.GetCategoryAsync(filter.CategoryId);

				if (category != null)
				{
					const string any = "any";

					ProductFilter productFilter = new ProductFilter();
					productFilter.CategoryId = filter.CategoryId;
					productFilter.CurrentPage = filter.CurrentPage;
					productFilter.PageSize = PAGE_SIZE;
					productFilter.Properties = filter.Properties
						.Where(p => p.Id > 0 && !string.IsNullOrEmpty(p.Value) && p.Value != any)
						.Select(p => new PropertyFilter()
						{
							PropertyId = p.Id,
							Value = p.Value,
							IsRange = p.IsRange,
							Operation = p.Operator
						})
						.ToArray();

					ProductPage page = await _productPageRepository.GetProductPage(productFilter);

					if (page != null)
					{
						ProductPageView view = new ProductPageView();
						view.CurrentPage = filter.CurrentPage;
						view.TotalPages = page.TotalPages;
						view.CategoryName = category.Name;
						view.Products = page.Products.Select(p => new ProductView()
						{
							Id = p.Id,
							Name = p.Name,
							ShortInfo = p.ShortInfo,
							UrlName = p.UrlName
						});

						return PartialView("_ShortProduct", view);
					}
				}
			}

			return View("Error");
		}


		[HttpGet, Route("items/{category}")]
		public async Task<IActionResult> Index(string category)
		{
			if (!string.IsNullOrEmpty(category))
			{
				Category dbCategory = await _categoryRepository.GetCategoryAsync(category);

				if (dbCategory != null)
				{
					ProductFilter productFilter = new ProductFilter()
					{
						CategoryId = dbCategory.Id,
						CategoryName = dbCategory.Name,
						CurrentPage = 1,
						PageSize = PAGE_SIZE
					};

					ProductPage productPage = await _productPageRepository.GetProductPage(productFilter);

					if (productPage != null)
					{
						ProductPageView page = new ProductPageView();

						page.CategoryName = dbCategory.Name;
						page.CategoryViewName = dbCategory.ViewName;
						page.CategoryId = dbCategory.Id;
						page.CurrentPage = 1;
						page.TotalPages = productPage.TotalPages;

						IEnumerable<ProductFilterItem> filterItems = await _productFilterRepository.GetProductFilterItems(dbCategory.Id);

						if (productPage.Products != null)
						{
							page.Products = productPage.Products.Select(p => new ProductView()
							{
								Id = p.Id,
								Name = p.Name,
								ShortInfo = p.ShortInfo,
								UrlName = p.UrlName
							});
						}

						if (filterItems != null)
						{
							page.FilterItems = filterItems.Select(i => new FilterItemView()
							{
								PropertyId = i.PropertyId,
								FilterItemType = i.FilterItemType,
								PropertyName = i.Property.Name,
								FilterItemValues = i.ProductFilterItemValues != null ? i.ProductFilterItemValues.Select(v => v.Value) : null
							});
						}

						return View(page);
					}
				}
			}

			return View("Error");
		}

		[HttpGet, Route("item/{productId:int}")]
		public async Task<IActionResult> GetProduct(int productId = 0)
		{
			if (productId > 0)
			{
				Product product = await _productRepository.GetProductAsync(productId);

				if (product != null)
				{
					FullProductView productView = GetFullProductView(product);

					return View("Product", productView);
				}
			}

			return View("Error");
		}

		[HttpGet, Route("items/{category}/{urlName}")]
		public async Task<IActionResult> GetProduct(string category, string urlName)
		{
			if (!string.IsNullOrEmpty(category) && !string.IsNullOrEmpty(urlName))
			{
				Product product = await _productRepository.GetProductAsync(category, urlName);

				if (product != null)
				{
					FullProductView productView = GetFullProductView(product);

					return View("Product", productView);
				}
			}

			return View("Error");
		}

		private FullProductView GetFullProductView(Product product)
		{
			FullProductView productView = new FullProductView();

			productView.ProductId = product.Id;
			productView.ProductName = product.Name;

			//productView.BaseProperties = product.ProductToProperty
			//	.Select(s => new ProductBaseProperty()
			//	{
			//		Id = s.Property.BaseProperty.Id,
			//		Name = s.Property.BaseProperty.Name
			//	})
			//	.Distinct()
			//	.ToArray();

			productView.Properties = product.ProductToProperty
				.Select(s => new ProductPropertyView()
				{
					PropertyId = s.PropertyId,
					PropertyName = s.Property.Name,
					BasePropertyId = s.Property.BaseProperty.Id,
					Value = s.Value,
					SizeValue = s.SizeValue
				}).ToArray();

			return productView;
		}

		protected override void Dispose(bool disposing)
		{
			if (disposing)
			{
				_productRepository.Dispose();
				_categoryRepository.Dispose();
				_productFilterRepository.Dispose();
			}

			base.Dispose(disposing);
		}
	}
}

WebEngine.Web/Controllers/ProductOfferController.cs
// -----------------------------------------------------------------------
// <copyright file="ProductOfferController.cs" author="Dzmitry Prakapenka">
//     All rights reserved.
// </copyright>
// -----------------------------------------------------------------------

namespace WebEngine.Web.Controllers
{
	#region Usings

	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Threading.Tasks;
	using Microsoft.AspNetCore.Mvc;
	using WebEngine.Web.ViewModels.ProductOffer;
	using Core.Interfaces;
	using Core.Entities;
	using Microsoft.AspNetCore.Authorization;

	#endregion

	/// <summary>
	/// <see cref="ProductOfferController"/> controller.
	/// </summary>
	//[Route("offers")]
	public class ProductOfferController : Controller
	{
		private readonly IProductOfferRepository _productOfferRepository;

		private readonly IStoreRepository _storeRepository;

		public ProductOfferController(
			IProductOfferRepository productOfferRepository,
			IStoreRepository storeRepository)
		{
			_productOfferRepository = productOfferRepository;
			_storeRepository = storeRepository;
		}

		[Authorize, HttpGet]
		public async Task<IActionResult> SaveOffer(int productId)
		{
			if (productId > 0)
			{
				Store store = await _storeRepository
					.GetStoreForUser(HttpContext.User.Identity.Name);

				if (store != null)
				{
					SaveOfferView offer = new SaveOfferView();
					offer.ProductId = productId;
					offer.StoreId = store.Id;

					return View("SaveOffer", offer);
				}
			}

			return View("Error");
		}

		[Authorize, HttpPost]
		public async Task<IActionResult> SaveOffer([FromForm] SaveOfferView offer)
		{
			if (offer != null)
			{
				ProductOffer dbOffer = new ProductOffer();
				dbOffer.ProductId = offer.ProductId;
				dbOffer.IsActive = true;
				dbOffer.Message = offer.Message;
				dbOffer.StoreId = offer.StoreId;
				dbOffer.Date = DateTime.UtcNow;

				bool success = await _productOfferRepository.SaveProductOfferAsync(dbOffer);

				if (success)
				{
					return RedirectToAction("Index","Home");
				}

				return View("SaveOffer", offer);
			}

			return View("Error");
		}

		public async Task<IActionResult> GetProductOffers(int productId)
		{
			if (productId > 0)
			{
				IEnumerable<ProductOffer> offers = await _productOfferRepository.GetProductOffersAsync(productId);

				if (offers != null)
				{
					IEnumerable<ProductOfferView> viewModel = offers.Select(o => new ProductOfferView()
					{
						Id = o.Id,
						ProductId = o.ProductId,
						StoreId = o.StoreId,
						StoreName = o.Store.Name,
						Message = o.Message
					});

					return View("GetProductOffers", viewModel);
				}
			}

			return View("Error");
		}

		protected override void Dispose(bool disposing)
		{
			if (disposing)
			{
				_productOfferRepository.Dispose();
			}

			base.Dispose(disposing);
		}
	}
}

WebEngine.Web/Views/Product/Index.cshtml
@*
	-----------------------------------------------------------------------
		<copyright file="Index.cshtml" author="Dzmitry Prakapenka">
			All rights reserved.
		</copyright>
	-----------------------------------------------------------------------
*@

@model WebEngine.Web.ViewModels.Product.ProductPageView

@{
	ViewData["Title"] = Model.CategoryViewName;
}

<div class="col-sm-3">
	<div class="left-sidebar">
		<h2>filter</h2>
		<div class="panel-group category-products" id="accordian">
			@*@await Component.InvokeAsync("FilterView", new { category = Model.CategoryName })*@

			@Html.Partial("_ProductFilter", Model.FilterItems)
		</div>
	</div>
</div>
<div class="col-sm-9 padding-right">
	<div class="features_items">
		<h2 class="title text-center">@Model.CategoryViewName</h2>
		<div id="view">

		</div>
	</div>
	<div id="pagination" class="text-center"></div>
</div>


@section Scripts {
	<script>
		'use strict';

		$(document).ready(function() {
			class Filter {
				constructor(categoryId, currentPage , properties) {
					this.CategoryId = categoryId;
					this.CurrentPage = currentPage;
					this.Properties = properties;
				}
			}
			class FilterItem{
				constructor(id, value, isRange, operator) {
					this.Id = id;
					this.Value = value;
					this.IsRange = isRange;
					this.Operator = operator;
				}
			}

			let categoryId = @Model.CategoryId;

			let totalPages = @Model.TotalPages;

			let elements = @Html.Raw(Json.Serialize(Model.FilterItems.Select(m => new { PropertyId = m.PropertyId, FilterItemType = m.FilterItemType })));

			let pag = $('#pagination').simplePaginator({
				totalPages: 1,
				maxButtonsVisible: 5,
				currentPage: 1,
				firstLabel: 'First',
				lastLabel: 'Last',
				clickCurrentPage: false,
				pageChange: onSelectPage
			});

			for(let i = 0; i < elements.length; i++) {

				if(elements[i].FilterItemType == 'DropDownList'){

					$('#'+elements[i].PropertyId).change(function(){
						pag.simplePaginator('changePage', 1);
					});

				} else if(elements[i].FilterItemType == 'Range'){

					$('#first'+elements[i].PropertyId).change(function(){
						pag.simplePaginator('changePage', 1);
					});
					$('#second'+elements[i].PropertyId).change(function(){
						pag.simplePaginator('changePage', 1);
					});
				}
			}

			function GrabFilter(currentPage) {

				let model = new Filter(categoryId, currentPage, [])

				for(let i = 0; i < elements.length; i++) {
					if(elements[i].FilterItemType == 'DropDownList') {
						let value = $('#'+elements[i].PropertyId).val();
						let property = new FilterItem(elements[i].PropertyId, value, false, '=')
						model.Properties.push(property);
					} else if(elements[i].FilterItemType == 'Range'){
						let value1 = $('#first'+elements[i].PropertyId).val();
						let property1 = new FilterItem(elements[i].PropertyId, value1, true, '>')
						model.Properties.push(property1);
						let value2 = $('#second'+elements[i].PropertyId).val();
						let property2 = new FilterItem(elements[i].PropertyId, value2, true, '<')
						model.Properties.push(property2);
					}
				}

				//temp value
				//model.Properties.push(new FilterItem(4, '11', false));

				return model;
			}

			function onSelectPage (page) {
				//saveHistory(document.location, page);

				let model = GrabFilter(page);
				Send(model);
			}

			function Send(model) {
				let filter = JSON.stringify(model);

				$.ajax({
					type: 'POST',
					url: '/Product/Index',
					contentType: 'application/json; charset=utf-8',
					data: filter
				}).success(function (data) {
					var domElement = $(data);
					$('div#view').replaceWith(domElement);

					pag.simplePaginator('setTotalPages', $('#totalPages').val());

				}).fail(function (data) {
					alert("I'm sorry. An error occurred while processing your request.");
				});
			}

			onSelectPage(1);

			//function saveHistory(url, page) {
			//	let u = url.origin + url.pathname +'#page='+page;
			//	window.history.pushState(null, null, u);
			//}

			//$(window).bind('popstate', function () {
			//	document.location.href = location.pathname;
			//});
		});
	</script>
}

WebEngine.Web/Views/Product/Product.cshtml
@*
	-----------------------------------------------------------------------
		<copyright file="Product.cshtml" author="Dzmitry Prakapenka">
			All rights reserved.
		</copyright>
	-----------------------------------------------------------------------
*@
@using WebEngine.Web.ViewModels.Product
@model WebEngine.Web.ViewModels.Product.FullProductView

<div class="col-sm-3">
	<div class="left-sidebar">
		@await Component.InvokeAsync("CategoryList")
	</div>
</div>
<div class="col-sm-9 padding-right">
	<div class="features_items">
		<h2 class="title text-center">@Model.ProductName</h2>
		<div class="product-details col-sm-9">
			<div class="col-sm-6">
				<div class="view-product">
					@*<img src="images/product-details/1.jpg" alt="" />*@
					<h3>ZOOM</h3>
				</div>
				<div id="similar-product" class="carousel slide" data-ride="carousel">

					<div class="carousel-inner">
						@*<div class="item active">
								<a href=""><img src="images/product-details/similar1.jpg" alt=""></a>
								<a href=""><img src="images/product-details/similar2.jpg" alt=""></a>
								<a href=""><img src="images/product-details/similar3.jpg" alt=""></a>
							</div>
							<div class="item">
								<a href=""><img src="images/product-details/similar1.jpg" alt=""></a>
								<a href=""><img src="images/product-details/similar2.jpg" alt=""></a>
								<a href=""><img src="images/product-details/similar3.jpg" alt=""></a>
							</div>
							<div class="item">
								<a href=""><img src="images/product-details/similar1.jpg" alt=""></a>
								<a href=""><img src="images/product-details/similar2.jpg" alt=""></a>
								<a href=""><img src="images/product-details/similar3.jpg" alt=""></a>
							</div>*@
					</div>

					<a class="left item-control" href="#similar-product" data-slide="prev">
						<i class="fa fa-angle-left"></i>
					</a>
					<a class="right item-control" href="#similar-product" data-slide="next">
						<i class="fa fa-angle-right"></i>
					</a>
				</div>
			</div>
			<div class="col-sm-6">
				<div class="product-information">
					@Model.ProductName
				</div>
			</div>

			<div class="col-sm-12">
				<br />
				<table class="table table-bordered">
					@foreach (ProductPropertyView property in Model.Properties)
					{
						<tr>
							<td>@property.PropertyName</td>
							<td>@property.Value @property.SizeValue</td>
						</tr>
					}
				</table>
			</div>
		</div>
		<div class="col-sm-3">
			<a asp-action="SaveOffer" asp-controller="ProductOffer" asp-route-productId="@Model.ProductId">Add Offer</a>

			@await Component.InvokeAsync("OfferComponent", new { productId = Model.ProductId })
		</div>
	</div>
</div>

WebEngine.Web/Views/Product/_ProductFilter.cshtml
@*
	-----------------------------------------------------------------------
		<copyright file="_ProductFilter.cshtml" author="Dzmitry Prakapenka">
			All rights reserved.
		</copyright>
	-----------------------------------------------------------------------
*@

@model IEnumerable<WebEngine.Web.ViewModels.Product.FilterItemView>

<div id="filter">
	@foreach (var filterItem in Model)
	{
		@if (filterItem.FilterItemType == "DropDownList")
		{
			<label class="control-label">@filterItem.PropertyName</label>

			<select id="@filterItem.PropertyId" class="form-control">
				<option value="any" selected="selected">Any</option>
				@foreach (var item in filterItem.FilterItemValues)
				{
					<option value="@item">@item</option>
				}
			</select>
		}
		else if (filterItem.FilterItemType == "Range")
		{
			<label class="control-label">@filterItem.PropertyName</label>

			<div id="@filterItem.PropertyId">
				<div class="input-group">
					<input type="text" id="@string.Concat("first", filterItem.PropertyId)" class="first form-control" />
					<span class="input-group-addon">-</span>
					<input type="text" id="@string.Concat("second", filterItem.PropertyId)" class="second form-control" />
				</div>
			</div>
		}
	}
</div>

WebEngine.Web/Views/Product/_ShortProduct.cshtml
@*
	-----------------------------------------------------------------------
		<copyright file="_ShortProduct.cshtml" author="Dzmitry Prakapenka">
			All rights reserved.
		</copyright>
	-----------------------------------------------------------------------
*@
@model WebEngine.Web.ViewModels.Product.ProductPageView
<div id="view">
	@foreach (var product in Model.Products)
	{
		<div class="col-sm-4">
			<div class="product-image-wrapper">
				<div class="single-products">
					<div class="productinfo text-center">
						@*<img src="~/images/No_image.png" alt="" />*@
						<h2>@product.Name</h2>
						<p>@product.ShortInfo</p>
						@*<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>*@
					</div>
				</div>
				<div class="choose">
					<ul class="nav nav-pills nav-justified">
						@*<li><a href="#"><i class="fa fa-plus-square"></i>Add to wishlist</a></li>*@
						<li>
							<a asp-action="GetProduct" asp-controller="Product" asp-route-category="@Model.CategoryName" asp-route-urlName="@product.UrlName">
								<i class="fa fa-plus-square"></i>More...
							</a>
						</li>
					</ul>
				</div>
			</div>
		</div>
	}

	@Html.Hidden("totalPages", Model.TotalPages, new { id = "totalPages" })
	@Html.Hidden("currentPage", Model.CurrentPage, new { id = "currentPage" })

</div>